//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class atencion_detalle
    {
        public int atencionID { get; set; }
        public int odontogramaID { get; set; }
        public int dienteID { get; set; }
        public int parteID { get; set; }
        public int diagnosticoID { get; set; }
        public int procedimientoID { get; set; }
        public string realizado { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual atencion atencion { get; set; }
        public virtual odontograma_detalle odontograma_detalle { get; set; }
    }
}
