//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class odontograma_detalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public odontograma_detalle()
        {
            this.atencion_detalle = new HashSet<atencion_detalle>();
        }
    
        public int odontogramaID { get; set; }
        public int dienteID { get; set; }
        public int parteID { get; set; }
        public int diagnosticoID { get; set; }
        public int procedimientoID { get; set; }
        public string realizado { get; set; }
        public Nullable<int> estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atencion_detalle> atencion_detalle { get; set; }
        public virtual diente diente { get; set; }
        public virtual odontograma odontograma { get; set; }
        public virtual tratamiento diagnostico { get; set; }
        public virtual parte parte { get; set; }
        public virtual tratamiento procedimiento { get; set; }
    }
}
